// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"kratos-app/internal/biz"
	"kratos-app/internal/conf"
	"kratos-app/internal/data"
	"kratos-app/internal/server"
	"kratos-app/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	greeterService := service.NewGreeterService(greeterUsecase)
	articleRepo := data.NewArticleRepo(dataData, logger)
	articleUsecase := biz.NewArticleUsecase(articleRepo, logger)
	blogService := service.NewBlogService(articleUsecase, logger)
	userRepo := data.NewUserRepo(dataData, logger)
	encryptService := biz.NewEncryptService(bootstrap)
	accountUseCase := biz.NewAccountUseCase(logger, bootstrap, userRepo, encryptService)
	accountService := service.NewAccountService(logger, accountUseCase)
	grpcServer := server.NewGRPCServer(confServer, greeterService, logger, blogService, accountService)
	httpServer := server.NewHTTPServer(confServer, greeterService, logger, blogService, accountService)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
